### PR TITLE
Improvements and fixes

### PR DESCRIPTION
**Pull request by attevaltojarvi**
Following https://github.com/akhundMurad/typeid-python/issues/9, here are the proposed improvements (plus some tests cleanup to get rid of warnings raised by pytest).

### CODE REVIEW

**Review by akhundMurad — APPROVED** [review]
Thank you again! @attevaltojarvi

**Comment by akhundMurad** [comment]
@attevaltojarvi please resolve the issues

**Comment by attevaltojarvi** [comment]
Apparently the CI runs in python 3.10 whereas I'm running python 3.11, and `int.from_bytes()` received a default argument for the `byteorder` parameter in the latter. I'll add it :+1:

**Comment by attevaltojarvi** [comment]
@akhundMurad seems that the spec has just been updated: https://github.com/jetify-com/typeid/commit/26a84e85491203834ed0d1c3423ba5f679a67114

How would you like to handle this? It now causes the spec tests to fail, unrelated to these other changes.

**Comment by akhundMurad** [comment]
@attevaltojarvi Yep, I am aware. Planning to create a new MR.

**Comment by akhundMurad** [comment]
Hello @attevaltojarvi. Could you please pull the main branch? I want to run tests and then include your PR in the release.

**Comment by attevaltojarvi** [comment]
Done!

**Pull request merged**
